### DISCUSSION TITLE
Access STIG Manager outside of localhost

### DISCUSSION THREAD

**Discussion by lowrider1064** [NUWCDIVNPT/stig-manager#1002] [Q&A]
Hey Everyone.

I just started this trek a few weeks ago and learning alot about Docker.  I was able to get everything setup and running while inside of "localhost" , but no matter what I change,  I keep getting the error  "Cannot read properties of undefined (reading 'digest')".  Which I am assuming is because of certificate issues.  I am just wondering where I go from here to be able to access this outside of localhost.  I have already created a certificate, but not quite sure where to insert it.  Any help would be greatly appreciated.

This is my current docker-compose.yml

```
# STIG Manager docker-compose orchestration

version: '3.3'

services:
  auth:
    image: nuwcdivnpt/stig-manager-auth
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/dock01.pem
      - KC_HTTPS_CERTIFICATE_KEY=/opt/keycloak/conf/dock01pk.pem
    volumes:
      - /usr/stigman/certs/dock01.pem:/opt/keycloak/conf/dock01.pem
      - /usr/stigman/certs/dock01pk.pem:/opt/keycloak/conf/dock01pk.pem
  db:
    image: mysql:8.0
    ports:
      - "50001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=stigman
      - MYSQL_PASSWORD=stigman
      - MYSQL_DATABASE=stigman
    cap_add:
      - SYS_NICE  # workaround MySQL logging bug => mbind: Operation not permitted 
  api:
    image: nuwcdivnpt/stig-manager:latest
    environment:
      - STIGMAN_OIDC_PROVIDER=http://auth:8080/realms/stigman
      - STIGMAN_CLASSIFICATION=U
      - STIGMAN_DB_HOST=db
      - STIGMAN_DB_PASSWORD=stigman
      - STIGMAN_INIT_IMPORT_STIGS=true
      # Change envvar below if non-localhost browsers will access the API
      - STIGMAN_CLIENT_OIDC_PROVIDER=https://hostname:8443/realms/stigman


    init: true
    ports:
      - "54000:54000"
```
