### ISSUE TITLE
GET STIG ccis endpoint returning 500 errors

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#100]
**Bug Location**

I found a bug in the:
- [x] API
- [ ] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**
500 Internal Server Error response to:
GET stigs/ccis/{cci}
GET stigs/{benchmarkId}/revisions/{revisionString}/ccis

TEST NOTES:
Tests exist for this endpoint, but currently commented out in block starting with:
"START AZDO #117"

**Comment by cd-rite** [comment]
Candidate SQL for these endpoints:
(need to be parameterized)

**GET stigs/ccis/{cci}:**

select c.cci, c.status, c.publishdate, c.contributor, c.type, c.definition, 
case when c.apAcronym
	is null
	then '{}'
	else
	json_object('apAcronym', c.apAcronym,
	'implementation', c.implementation,
	'assessmentProcedure', c.assessmentProcedure)
end
	as 'emassAp',
coalesce((select json_arrayagg(
	json_object('creator', crm.creator,
	'title', crm.title))
	from cci_reference_map crm
	where crm.cci = c.cci), json_array())
	as 'references',
coalesce(
	(select json_arrayagg(stig)
	from
	(select distinct
	json_object('benchmarkId', rv.benchmarkId,
	'revisionStr', concat('V', rv.version, 'R', rv.release))
	as 'stig'
	from cci ci
	left join rule_cci_map as rcm on rcm.cci = ci.cci
	left join rev_group_rule_map as rgrm on rgrm.ruleId = rcm.ruleId
	left join rev_group_map as rgm on rgm.rgId = rgrm.rgId
	left join revision as rv on rv.revId = rgm.revId
	where ci.cci = c.cci and benchmarkId is not null
	) as agg)
	, json_array())
	as stigs
from cci c	
-- where c.cci = "000001"


**GET stigs/{benchmarkId}/revisions/{revisionString}/ccis:**

select json_arrayagg(ccis)
from
(select distinct json_object( 'cci', c.cci, 'type', c.type, 'references',
coalesce((select json_arrayagg(
	json_object('creator', crm.creator, 
	'title', crm.title))
	from cci_reference_map crm
	where crm.cci = c.cci), json_array())
) as ccis
from revision rv
left join rev_group_map as rgm on rgm.revId = rv.revId
left join rev_group_rule_map as rgrm on rgrm.rgId = rgm.rgId
left join rule_cci_map as rcm on rgrm.ruleId = rcm.ruleId
left join cci as c on rcm.cci = c.cci
left join cci_reference_map as crm on crm.cci = c.cci
where rv.benchmarkId = "A10_Networks_ADC_ALG_STIG" and rv.version = "2" and rv.release = "1") as ccis

**Comment by csmig** [comment]
The OAS for this endpoint is also missing a query parameter for `projections`. A suggested addition to the `parameters` references would look like:
```
    CciProjectionQuery:
      name: projection
      in: query
      description: >
        Optional properties to return.
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string
          enum:
            - emassAp
            - references
            - stigs
```
