### ISSUE TITLE
metadataUri":"http://auth:8080/realms/stigman/.well-known/openid-configuration","message":"connect ECONNREFUSED

### ISSUE THREAD

**Issue by jeremyatourville** [NUWCDIVNPT/stig-manager#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [X] UI or other client
- [X] Deployment
- [ ] Elsewhere

### Current Behavior

1. Browsing to http://gsil-docker1.idm.x.x:54000 error is: `failed to get http://auth:8080/realms/stigman/.well-known/openid-configuration`
#This is bypassing the NGINX proxy

2. Browsing to https://stigman.idm.x.x/stigman results in error: `Cannot GET /stigman/`
#Using the proxy to get to STIG manager

3. Browsing to http://gsil-docker1.idm.x.x:8080 brings me to the keycloak page where I can login to the admin console
#This is bypassing the NGINX proxy

4. Browsing to https://stigman.idm.x.x/kc results in error message:  
```
502 Bad Gateway
```
#Using the proxy to get to keycloak

### Expected Behavior

Should not error when trying to connect.

### Steps To Reproduce

- Nginx is running as a reverse proxy.
- A cname DNS entry is created for stigman which points to the docker host on which it is running.
- We have our own CA server and the certificate is valid for subj alt name - stigman
- Nginx config is separated from the stig-manager config.
- Unsure if this parameter is correct:
```
#      Change envvar below if non-localhost browsers will access the API
      - STIGMAN_CLIENT_OIDC_PROVIDER=http://auth:8080/kc/realms/stigman

```
Configs for stig manager:

```
version: '3.7'

networks:
  stigman:

services:
  auth:
    image: gsil-docker1.idm.x.x:5000/stig-manager-auth:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=My_Password
      - KC_PROXY=edge
    ports:
      - "8080:8080"

  db:
    image: gsil-docker1.idm.x.x:5000/mysql8:8.0.31
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=My_root_Password
      - MYSQL_USER=stigman
      - MYSQL_PASSWORD=My_stigman_Password
      - MYSQL_DATABASE=stigman
    cap_add:
      - SYS_NICE  # workaround MySQL logging bug => mbind: Operation not permitted
    volumes:
      - ./mysql-data:/var/lib/mysql

  stigman:
    image: gsil-docker1.idm.x.x:5000/stig-manager:1.3.5
    environment:
      - STIGMAN_OIDC_PROVIDER=http://auth:8080/realms/stigman
      - STIGMAN_CLASSIFICATION=U
      - STIGMAN_DB_HOST=db
      - STIGMAN_DB_PASSWORD=stigmanpw
#      Change envvar below if non-localhost browsers will access the API
      - STIGMAN_CLIENT_OIDC_PROVIDER=http://localhost:8080/kc/realms/stigman
    init: true
    ports:
      - "54000:54000"
```
Configs for NGINX:
```
version: '3.7'

networks:
  default:
    name: docker_monitoring
    external: true
    name: mattermost_mattermost
    external: true
    name: gitlab_default
    external: true
    name: kibana
    external: true
    name: grafana_monitoring
    external: true
    name: guacamole_guacnetwork_compose
    external: true
    name: vault_default
    external: true
    name: stig-manager
    external: true
    name: loki_monitoring 
    external: true
    name: stigman-orchestration_default
    external: true
    name: node-exporter_monitoring
    external: true
    name: prometheus_monitoring
    external: true
    name: nginx_default
    external: false

services:
  nginx:
    image: gsil-docker1.idm.x.x:5000/nginx:1.23.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/localhost/nginx.crt:/etc/nginx/nginx.crt
      - ./certs/localhost/nginx.key:/etc/nginx/nginx.key
      - ./certs/dod/gsil-ipa-chain.crt:/etc/nginx/gsil-ipa-chain.crt
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    ports:
    - "443:443"
    - "80:80"
    restart: unless-stopped
```
nginx.conf:
```
events {
  worker_connections  4096;  ## Default: 1024
}
pid        /var/cache/nginx/nginx.pid;
http {
    server {
        listen 443 ssl;
        server_name grafana.idm.x.x;
        ssl_certificate             /etc/nginx/gsil-ipa-chain.crt;
        ssl_certificate_key         /etc/nginx/nginx.key;
        location / {
            proxy_pass http://gsil-docker1.idm.x.x:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
        }
    }
    server {
        listen 443 ssl;
        server_name mattermost.idm.x.x;
        ssl_certificate             /etc/nginx/gsil-ipa-chain.crt;
        ssl_certificate_key         /etc/nginx/nginx.key;
        location / {
            proxy_pass http://gsil-docker1.idm.x.x:8065;
            proxy_set_header Host $host;
            proxy_set_header CLIENT_HOST $remote_addr;
            proxy_set_header Origin "";
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
        }
    }
    server {
          listen 443 ssl;
          server_name gitlab.idm.x.x;
          ssl_certificate             /etc/nginx/gsil-ipa-chain.crt;
          ssl_certificate_key         /etc/nginx/nginx.key;
          location / {
              proxy_pass http://gitlab.idm.x.x:8081;
              # proxy_set_header Host $host;
              # proxy_set_header X-Real-IP $remote_addr;
              # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              # proxy_set_header X-Forwarded-Host $server_name;
          }
    }
    server {
        listen 443 ssl;
        server_name prometheus.idm.x.x;
        ssl_certificate             /etc/nginx/gsil-ipa-chain.crt;
        ssl_certificate_key         /etc/nginx/nginx.key;
        location / {
            proxy_pass http://gsil-docker1.idm.x.x:9090;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
        }
    }
    server {
        listen 443 ssl;
        server_name loki.idm.x.x;
        ssl_certificate             /etc/nginx/gsil-ipa-chain.crt;
        ssl_certificate_key         /etc/nginx/nginx.key;
        location / {
            proxy_pass http://gsil-docker1.idm.x.x:3100/ready;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
        }
    }
    server {
        listen 443 ssl;
        server_name vault.idm.x.x;
        ssl_certificate             /etc/nginx/gsil-ipa-chain.crt;
        ssl_certificate_key         /etc/nginx/nginx.key;
        location / {
            proxy_pass http://gsil-docker1.idm.x.x:8200;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
        }
    }
    server {
        listen 443 ssl;
        server_name guacamole.idm.x.x;
        ssl_certificate             /etc/nginx/gsil-ipa-chain.crt;
        ssl_certificate_key         /etc/nginx/nginx.key;
        location / {
            proxy_pass http://gsil-docker1.idm.x.x:8082/guacamole/;
            proxy_buffering off;
	    proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection $http_connection;
            proxy_set_header X-Forwarded-Host $server_name;
	    access_log off;
        }
    }

        upstream auth {
        server 127.0.0.1:8080;
        }
    server {
        listen 443 ssl;
        server_name stigman.idm.x.x;
        ssl_certificate             /etc/nginx/gsil-ipa-chain.crt;
        ssl_certificate_key         /etc/nginx/nginx.key;
        root                        /usr/share/nginx/html;
        client_max_body_size        100M;
        ssl_prefer_server_ciphers   on;
        ssl_client_certificate      /etc/nginx/gsil-ipa-chain.crt;
        ssl_verify_client           optional;
        ssl_verify_depth            4;
        error_log                   /var/log/nginx/error.log debug;
        if ($return_unauthorized) { return 496; }
        location / {
            autoindex on;
            ssi on;
        }
        
        location /stigman/ {
            proxy_pass              http://stigman:54000;
        }
        
        location /kc/ {
            proxy_pass              http://auth;
            proxy_set_header        Host               $host;
            proxy_set_header        X-Real-IP          $remote_addr;
            proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Host   $host;
            proxy_set_header        X-Forwarded-Server $host;
            proxy_set_header        X-Forwarded-Port   $server_port;
            proxy_set_header        X-Forwarded-Proto  $scheme;
            proxy_set_header        ssl-client-cert    $ssl_client_escaped_cert;
            proxy_buffer_size       128k;
            proxy_buffers           4 256k;
            proxy_busy_buffers_size 256k;
        }

    }

    # define which endpoints require mTLS
    map_hash_bucket_size 128;
    map $uri $secured_url {
        default false;
        "/kc/realms/stigman/protocol/openid-connect/auth" true;
    }

    map "$secured_url:$ssl_client_verify" $return_unauthorized {
            default 0;
            "true:FAILED" 1;
            "true:NONE" 1;
            "true:" 1;
    }
}
```

Note:  If I remove 
```
 upstream auth {
        server 127.0.0.1:8080;
        }
```
and change 
`proxy_pass              http://auth;` to `proxy_pass              http://auth:8080;`

then nginx will not start properly, I get message 
```
nginx-nginx-1  | 2023/05/18 14:14:04 [emerg] 1#1: host not found in upstream "auth" in /etc/nginx/nginx.conf:130
nginx-nginx-1  | nginx: [emerg] host not found in upstream "auth" in /etc/nginx/nginx.conf:130
nginx-nginx-1 exited with code 1
```

### Can you provide screenshots, logs, or other useful artifacts?

Here is the log from startup
 
[stig-manager-startup.txt](https://github.com/NUWCDIVNPT/stig-manager/files/11510825/stig-manager-startup.txt)

### Describe your Environment

```markdown
- Hosting: Docker server running on Rocky 8.7 (self hosted )
- Browser: Chromium and Firefox
- OS: Centos 7.9
- Node: N/A
- npm: N/A

I presume the most important error to fix is ECONNREFUSED.  Why am I getting that when going to the server?  I also understand that the errors shown will depend on if your are bypassing the proxy or trying to use the proxy directly.
```
