### ISSUE TITLE
FEATURE REQUEST: Breakout desired status for each valid evaluation result type in importOptions

### ISSUE THREAD

**Issue by alexisdafonseca** [NUWCDIVNPT/stig-manager#1442]
Original User request: 
In STIGMan OSS collection settings for import options, would it be possible to extend the behavior for set review status to accept but based on each type of specific results (NF, NA, etc.)

Dev description:
Subissues:
stig-manager-client-modules: [40](https://github.com/NUWCDIVNPT/stig-manager-client-modules/issues/40) - actual processing implementation to be based on these changes
STIG Manager UI: #1606 -changes to allow user to set granular import options

OAS changes:
The Collection settings.importOptions schema currently supports an "autoStatus" property defined with an enum. 
To support granular import options autoStatus should become an object with keys for each valid evaluation result:
```
fail
notapplicable
pass
```
Each key's values should be strings defined by the current autoStatus enum:
```
  - "null"
  - saved
  - submitted
  - accepted
```

new OAS To support this:
```
    CollectionImportAutoStatus:
      type: object
      additionalProperties: false
      description: |
        Determines how to set the status property of imported reviews for each evaluation result.
        Each property must be one of:
         - 'null': Don't set a status (Keep existing Review Status)
         - 'saved': Always set status to 'saved'
         - 'submitted': Set status to 'submitted' if the review is submittable per Collection settings
         - 'accepted': Set status to 'accepted' if the review is submittable, and User has permission to accept,  otherwise 'submitted'
      properties:
        fail:
          type: string
          enum:
            - "null"
            - saved
            - submitted
            - accepted
        notapplicable:
          type: string
          enum:
            - "null"
            - saved
            - submitted
            - accepted
        pass:
          type: string
          enum:
            - "null"
            - saved
            - submitted
            - accepted
      required:
      - fail
      - notapplicable
      - pass
.................
``` 

A migration will also be needed in order take existing import options auto status values and map them to the new object. 

The behavior will be as following 

before migration:
```
autoStatus = saved
```

after migration:
```
  autoStatus: {
    fail: "saved",
    notapplicable: "saved",
    pass: "saved",
  }
```
