### ISSUE TITLE
Refactor the metadata properties

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stig-manager#286]
To support emerging use cases that require keys that occur multiple times.

The new OpenAPI spec:
```
Metadata:
  type: array
  items:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
```
