### ISSUE TITLE
BUG: Data lost on restart

### ISSUE THREAD

**Issue by huntermcd** [NUWCDIVNPT/stig-manager#464]
When restarting the containers all of the previous data has been lost; reading other projects some of the recommendations are either to not use docker-compose or to use a volume for the db.  I think the docker-compose.yml should be, adding a restart: always and a max log size to avoid filling the /usr/lib/docker partition;

```
version: '3.7'

services:
  auth:
    logging:
            driver: "json-file"
            options:
                max-size: "50m"
    restart: always
    image: nuwcdivnpt/stig-manager-auth
    ports:
      - "8080:8080"
  db:
    logging:
            driver: "json-file"
            options:
                max-size: "50m"
    restart: always
    image: mysql:8.0
    ports:
      - "50001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=stigman
      - MYSQL_PASSWORD=stigman
      - MYSQL_DATABASE=stigman
    cap_add:
      - SYS_NICE  # workaround MySQL logging bug => mbind: Operation not permitted
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    logging:
            driver: "json-file"
            options:
                max-size: "50m"
    restart: always
    image: nuwcdivnpt/stig-manager
    environment:
      - STIGMAN_OIDC_PROVIDER=http://auth:8080/auth/realms/stigman
      - STIGMAN_CLASSIFICATION=U
      - STIGMAN_DB_HOST=db
      - STIGMAN_DB_PASSWORD=stigman
      - STIGMAN_INIT_IMPORT_STIGS=true
      - STIGMAN_INIT_IMPORT_SCAP=true
      # Change envvar below if non-localhost browsers will access the API
      - STIGMAN_CLIENT_OIDC_PROVIDER=http://localhost:8080/auth/realms/stigman
    init: true
    ports:
      - "54000:54000"
volumes:
  mysql_data:
```
